spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ranjeetkumar274/configuration-properties
          clone-on-start: true
management:
  security:
    enabled: false

server:
  port: 8888